ci:
  collect:
    numberOfRuns: 1
    staticDistDir: ./_site
    url:
      - http://localhost/
      - http://localhost/projects
      - http://localhost/funding/seed-grants
  assert:
    assertions:
      categories:performance: off
      categories:pwa: off
