title: 'NYU DH'
full_title: 'NYU Digital Humanities'
tagline: >
  NYU DH focuses on new technologies, advanced computing, and public engagement to inform and interrogate humanistic inquiry.
timezone: UTC
email: dh.help@nyu.edu

semester:
  current: 'Spring 2022'
  next: 'Fall 2022'

baseurl: ''
url: ''
future: true
show_footer: true
source: source
theme: nyu-dh-theme
plugins:
  - pagemaster

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown

collections:
  news:
    output: true
  testimonials:
    output: true
  projects:
    output: true
    source: projects.yml
    id_key: pid
    layout: project

defaults:
  - scope:
      type: news
    values:
      layout: page
