theme: nyu-dh-theme
tagline: 'Digital Humanities at New York University'
fixed_navbar: true

title: nyu/dh
timezone: UTC
email: dh.help@nyu.edu
description: "Here you'll find sit amet, consectetur adipiscing elit. Sed eu elit in diam congue vehicula non sed magna. Aenean sit amet odio auctor, bibendum est eget, ultricies justo. Phasellus aliquam diam nec purus tincidunt lacinia. Duis eu porta enim, a fermentum eros. Phasellus placerat rutrum molestie."

baseurl: ''
url: ''
future: true
source: src
show_footer: false

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown
