theme: nyu-dh-theme

title: 'NYU DH'
full_title: 'NYU Digital Humanities'
tagline: >
  NYU DH focuses on new technologies, advanced computing, and public engagement to inform and interrogate humanistic inquiry.
timezone: UTC
email: dh.help@nyu.edu

baseurl: ''
url: ''
future: true
show_footer: true
source: src

permalink: pretty
logo-image-url: images/logo.png
github_username: 'nyu-dh'
twitter_username: 'nyu_dh'
markdown: kramdown

collections:
  news:
    output: true

collections:
  news:
    output: true

defaults:
  - scope:
      type: news
    values:
      layout: page
