
name: ci:test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: install ruby
        uses: ruby/setup-ruby@v1
      - name: install gems
        run: bundle install
      - name: build
        run: bundle exec rake build
      - name: test
        run: bundle exec rake test
